
const SampleJson = [
    {
        id:1,
        title: "알통끝판왕인 가평 닭갈비 맛집 소개",
        text: "알통 며칠 전 가평에 들렀다가 이 근처에서 장작구이로 엄청 유명하다는 가평 닭갈비 맛집을 찾았는데요. 쫄깃한 닭갈비에 막국수까지 먹어주니 같이 방문한 지인들 모두에게 만족을 안겨준 식당이에요. 1. 아침고요 장작구이 숯불닭갈비 13,000원, ...",
        profile: 'profile01.jpg',
        nickname: 'Vivien',
        backImg: 'bg06.jpg',
        time: 1612292323330,
        view: 16,
        reply: 12,
        hunAl: 1000,
        take: 40,
        good: 230
    },
    {
        id:2,
        title: "알통제주도민들로부터 가장 사랑받는 사라봉공원",
        text: "제주도민들로부터 가장 사랑받는 사라봉공원 제주도 수많은 오름 중에 제주도민들로부터 가장 사랑받는 오름을 들라면, 아마도 사라봉공원을 꼽을 것이다. 제주도 오름 사라봉공원은 예로부터 지는 해가 아름다워 ‘사봉낙조’라 하여 영주십경...",
        profile: 'profile02.jpg',
        nickname: '고양이',
        backImg: 'bg01.jpg',
        time: 1608255682130,
        view: 6,
        reply: 12,
        hunAl: 2000,
        take: 39,
        good: 20
    },
    {
        id:3,
        title: "알통퓨어원데이 도톰한 덴탈 블랙마스크 국내산이라 안심",
        text: "퓨어원데이 도톰한 덴탈 블랙마스크 안전한 마스크 100% 국내생산 마스크 퓨어원데이 덴탈마스크입니다. 이젠 마스크 하는 일이 더 자연스럽고 당연한 요즘인 거 같아요. 작년에만 해도 아침에 깜빡하고 나가서 다시 집에 돌아오기를 몇 번 했...",
        profile: 'profile03.jpg',
        nickname: '서울인',
        backImg: 'bg02.jpg',
        time: 1618223870150,
        view: 10,
        reply: 33,
        hunAl: 3000,
        take: 29,
        good: 30
    },
    {
        id:4,
        title: "알통풍요로운 울진 맛집 리스트",
        text: "날이 너무나 좋았던 며칠 전 친구들과 기분전환 겸 울진으로 여행을 다녀왔어요. 바닷가 마을에 간 만큼 해산물을 먹기 위해 근처에서 가장 유명하다는 울진 맛집으로 향했어요. 싱싱한 재료만을 판매하고 있다는 이야기를 듣고 선택하였는데 ...",
        profile: 'profile04.jpg',
        nickname: '인천사람',
        backImg: 'bg03.jpg',
        time: 1618310408770,
        view: 22,
        reply: 120,
        hunAl: 4000,
        take: 34,
        good: 211
    },
    {
        id:5,
        title: "알통황순원 곡예사",
        text: "길잡이 피란살이에서 다지는 긍정의 희망 글로 풀어낸 전쟁의 참상, 황순원 ‘곡예사’ 해설 역시 황순원입니다. 힘들다는 말 한 마디도 없지만 전쟁의 참상을 보여주고, 나는 이겨낼거야라는 말 한마디도 없지만 내일에 대한 희망을 보여주는 ...",
        profile: 'profile02.jpg',
        nickname: '알통폐인',
        backImg: 'bg04.jpg',
        time: 1518420777820,
        view: 30,
        reply: 12,
        hunAl: 3500,
        take: 38,
        good: 11
    },
    {
        id:6,
        title: "알통초간단 계란국 끓이는법 아침식사 메뉴",
        text: "오늘은 아침식사 메뉴로 딱인 초간단 계란국 끓이는법을 소개해드릴게요 최근에는 건강을 챙기기 위해 간편식이라도 끼니를 꼭 챙기게 되는데요 하루 세끼를 꼬박꼬박 챙겨 먹어야 해서 밥 먹고 돌아서면 또 뭘 먹어야 할지 늘 고민이 되더라고...",
        profile: 'profile04.jpg',
        nickname: '인천사람',
        backImg: 'bg03.jpg',
        time: 1588583848640,
        view: 22,
        reply: 120,
        hunAl: 4000,
        take: 10,
        good: 55
    },
    {
        id:7,
        title: "알통뇌알통, 아름다운뇌미인 만들기",
        text: "이 생기잖아요 특히나 걷는운동을 많이하면 종아리가 딴딴해집니다. 이쁜치매는 자주 감사해하며 밝게 자주 웃는답니다. 무엇을 듣고, 무엇을 행동하고, 무엇을 생각하느냐에 따라 뇌세포가 변하면서 뇌에 ",
        profile: 'profile04.jpg',
        nickname: '알통',
        backImg: 'bg03.jpg',
        time: 1618584403170,
        view: 26,
        reply: 12,
        hunAl: 2300,
        take: 16,
        good: 56
    },
    {
        id:8,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:9,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:10,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:11,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:12,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:14,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:15,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:17,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:18,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:19,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:20,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:21,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:22,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:23,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:24,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:25,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:26,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:27,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:28,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:29,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:30,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:31,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:32,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:33,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:34,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
    {
        id:35,
        title: "알통의정부/용현동 알통떡강정 용현점-알통삼총사",
        text: "떡강정 용현점 [찾아가는 방법] 1. 용현동 우리은행 앞 건물 2. 한마음병원 앞 건물 3. 베르우스m 오피스텔 앞 건물 4. 송산역 바로 앞 오늘... ",
        profile: 'profile01.jpg',
        nickname: '내돈내산',
        backImg: 'bg06.jpg',
        time: 1618684403170,
        view: 138,
        reply: 125,
        hunAl: 10000,
        take: 349,
        good: 450
    },
]

export default SampleJson;
